import { useState } from "react";
import { View,Text,Pressable,ScrollView,Linking } from "react-native";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { makeStyles,useTheme,fonts,spacing,radius } from "@/src/theme";
import { Field,Button } from "@/src/components/ui";
import { Icon } from "@/src/components/Icon";
import { useToast } from "@/src/components/Toast";
import { useQuery } from "@tanstack/react-query";
import { api, fileUrl } from "@/src/api/client";

export default function AdminBlueControls(){
 const styles=useStyles();const {colors}=useTheme();const router=useRouter();const insets=useSafeAreaInsets();const toast=useToast();const [userId,setUserId]=useState("");const [reviewId,setReviewId]=useState("");const [note,setNote]=useState("");const [busy,setBusy]=useState(false);
 const pending=useQuery({queryKey:["admin-profile-reviews"],queryFn:()=>api.get("/admin/profile-change/reviews"),refetchInterval:15000});
 async function manual(enabled:boolean){if(!userId.trim())return toast.show("Enter user ID","error");setBusy(true);try{const r=await api.post("/admin/blue/manual",{user_id:userId.trim(),enabled});toast.show(enabled?"Blue Tick granted with benefits":"Manual Blue Tick removed","success");}catch(e:any){toast.show(e.message||"Action failed","error");}finally{setBusy(false)}}
 async function review(decision:"approved"|"rejected"){if(!reviewId.trim())return toast.show("Enter pending review ID","error");setBusy(true);try{await api.post("/admin/profile-change/review",{review_id:reviewId.trim(),decision,note:note.trim()||null});toast.show(`Profile change ${decision}`,"success");setReviewId("");setNote("");pending.refetch();}catch(e:any){toast.show(e.message||"Review failed","error");}finally{setBusy(false)}}
 return <View style={[styles.root,{paddingTop:insets.top}]}><View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Icon name="chevron-back" size={26} color={colors.onSurface}/></Pressable><Text style={styles.title}>Blue Tick Admin</Text><View style={{width:40}}/></View><ScrollView contentContainerStyle={styles.body}><View style={styles.card}><Text style={styles.cardTitle}>Manual Blue Tick Testing</Text><Text style={styles.sub}>Grant Blue without payment for testing. The account receives the same entitlement system. Removing the manual grant will not remove a separately active paid Blue status.</Text><Field value={userId} onChangeText={setUserId} placeholder="User ID"/><View style={styles.row}><Button title="Grant Blue" onPress={()=>manual(true)} loading={busy} style={{flex:1}}/><Button title="Remove" onPress={()=>manual(false)} disabled={busy} style={{flex:1}}/></View></View><View style={styles.card}><Text style={styles.cardTitle}>Verified Profile Change Review</Text><Text style={styles.sub}>Approve or reject pending Blue verified name/profile-photo changes. Cover photos do not enter this queue.</Text>{pending.isError&&<Text style={styles.sub}>Could not load reviews. Please reopen this page.</Text>}{(pending.data||[]).map((item:any)=><View style={styles.card} key={item.id}><Text style={styles.cardTitle}>{item.current_name} (@{item.username})</Text><Text style={styles.sub}>Requested: {item.changes?.full_name || "Profile photo change"}</Text>{[["ID document",item.name_evidence_url||item.avatar_evidence_url],["Live selfie",item.live_selfie_url]].map(([label,url])=>url&&<Pressable key={label} onPress={()=>Linking.openURL(fileUrl(url) || url!)}><Text style={{color:colors.info}}>View {label}</Text></Pressable>)}<Button title={reviewId===item.id?"Selected for review":"Select request"} onPress={()=>setReviewId(item.id)}/></View>)}<Field value={reviewId} onChangeText={setReviewId} placeholder="Pending review ID"/><Field value={note} onChangeText={setNote} placeholder="Admin note (optional)" multiline/><View style={styles.row}><Button title="Approve" onPress={()=>review("approved")} loading={busy} style={{flex:1}}/><Button title="Reject" onPress={()=>review("rejected")} disabled={busy} style={{flex:1}}/></View></View></ScrollView></View>;
}
const useStyles=makeStyles(c=>({root:{flex:1,backgroundColor:c.surface},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderBottomWidth:1,borderBottomColor:c.border},back:{width:40,height:40,alignItems:"center",justifyContent:"center"},title:{fontFamily:fonts.display,fontSize:18,color:c.onSurface},body:{padding:spacing.lg,gap:spacing.lg,paddingBottom:48},card:{gap:spacing.md,padding:spacing.lg,borderWidth:1,borderColor:c.border,borderRadius:radius.lg},cardTitle:{fontFamily:fonts.display,fontSize:17,color:c.onSurface},sub:{fontFamily:fonts.text,fontSize:13,lineHeight:19,color:c.onSurfaceSecondary},row:{flexDirection:"row",gap:spacing.sm}}));