import { useState } from "react";
import { View, Text, Pressable, TextInput, ScrollView } from "react-native";
import { Image } from "expo-image";
import { useAudioRecorder, RecordingPresets, AudioModule, setAudioModeAsync } from "expo-audio";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useQueryClient } from "@tanstack/react-query";
import { makeStyles, useTheme, fonts, spacing, radius, STORY_BG_COLORS } from "@/src/theme";
import { Button } from "@/src/components/ui";
import { Icon } from "@/src/components/Icon";
import { useToast } from "@/src/components/Toast";
import { api, fileUrl, uploadFile } from "@/src/api/client";
import { pickAndUploadImage, pickAndUploadStoryVideo } from "@/src/lib/media";
import { useBlueEntitlements } from "@/src/hooks/useBlueEntitlements";

export default function CreateStory() {
  const styles = useStyles(); const { colors } = useTheme(); const insets = useSafeAreaInsets(); const router = useRouter(); const toast = useToast(); const qc = useQueryClient();
  const blue = useBlueEntitlements();
  const canVideo = !!blue.data?.blue?.video_stories;
  const maxVideoSeconds = blue.data?.blue?.story_video_max_seconds || 60;
  const [mode, setMode] = useState<"text" | "photo" | "voice" | "video">("text");
  const [text, setText] = useState(""); const [bg, setBg] = useState(STORY_BG_COLORS[0]); const [image, setImage] = useState<string | null>(null); const [audio, setAudio] = useState<string | null>(null); const [audioDur, setAudioDur] = useState(0); const [video, setVideo] = useState<string | null>(null); const [videoDur, setVideoDur] = useState(0); const [recording, setRecording] = useState(false); const [recStart, setRecStart] = useState(0); const [audience, setAudience] = useState<"friends" | "inner">("friends"); const [busy, setBusy] = useState(false);
  const recorder = useAudioRecorder(RecordingPresets.HIGH_QUALITY);

  async function toggleRecord() { if (!recording) { try { const perm = await AudioModule.requestRecordingPermissionsAsync(); if (!perm.granted) return toast.show("Microphone permission needed", "error"); await setAudioModeAsync({ playsInSilentMode: true, allowsRecording: true }); await recorder.prepareToRecordAsync(); recorder.record(); setRecStart(Date.now()); setRecording(true); setAudio(null); } catch { toast.show("Could not start recording", "error"); } } else { try { await recorder.stop(); setRecording(false); const uri = recorder.uri; const dur = (Date.now()-recStart)/1000; if (!uri || dur < 1) return toast.show("Hold longer to record", "info"); setBusy(true); const url = await uploadFile(uri, `story_${Date.now()}.m4a`, "audio/m4a"); setAudio(url); setAudioDur(dur); toast.show("Voice recorded ✓", "success"); } catch(e:any){ toast.show(e.message||"Voice upload failed","error"); } finally { setBusy(false); } } }
  async function pickImage(){ setBusy(true); try { const r=await pickAndUploadImage({quality:.6,aspect:[9,16]}); if(r?.denied) toast.show("Photo permission needed","error"); else if(r?.url){setImage(r.url);setMode("photo");} } catch(e:any){toast.show(e.message||"Upload failed","error");} finally{setBusy(false);} }
  async function pickVideo(){ if(!canVideo) return toast.show("Video Stories are a Blue Tick benefit","info"); setBusy(true); try { const r=await pickAndUploadStoryVideo(maxVideoSeconds); if(r?.denied) toast.show("Media permission needed","error"); else if(r?.tooLong) toast.show(`Choose a video up to ${maxVideoSeconds} seconds`,`error`); else if(r?.url){setVideo(r.url);setVideoDur(r.duration);setMode("video");toast.show("Video ready ✓","success");} } catch(e:any){toast.show(e.message||"Video upload failed","error");} finally{setBusy(false);} }

  async function share(){ if(mode==="text"&&!text.trim()) return toast.show("Write something for your story","error"); if(mode==="photo"&&!image) return toast.show("Add a photo","error"); if(mode==="voice"&&!audio) return toast.show("Record a voice note first","error"); if(mode==="video"&&!video) return toast.show("Choose a video first","error"); setBusy(true); try { if(mode==="video") await api.post("/stories/video",{media:video,duration:videoDur,caption:text.trim()||null,audience}); else await api.post("/stories",{type:mode,text:mode!=="photo"?text.trim()||null:null,bg_color:mode!=="photo"?bg:null,image:mode==="photo"?image:null,media:mode==="voice"?audio:null,duration:mode==="voice"?audioDur:null,audience}); qc.invalidateQueries({queryKey:["stories"]}); toast.show("Story shared!","success"); router.back(); } catch(e:any){toast.show(e.message||"Could not share story","error");} finally{setBusy(false);} }

  return <View style={styles.root}>
    <View style={[styles.preview, mode!=="photo"&&mode!=="video"&&{backgroundColor:bg}]}>
      {mode==="photo"&&image&&<Image source={{uri:fileUrl(image)}} style={styles.previewImg} contentFit="cover"/>}
      {mode==="text"?<TextInput value={text} onChangeText={setText} placeholder="Type your story..." placeholderTextColor="rgba(255,255,255,0.6)" style={styles.storyInput} multiline maxLength={200}/>:mode==="voice"?<View style={styles.voiceWrap}><Pressable style={[styles.recBtn,recording&&{backgroundColor:"#EF4444"}]} onPress={toggleRecord}><Icon name={recording?"stop":audio?"checkmark":"mic"} size={40} color="#FFFFFF"/></Pressable><Text style={styles.voiceLabel}>{recording?"Recording... tap to stop":audio?`Voice ready · ${Math.round(audioDur)}s`:"Tap to record a voice drop"}</Text><TextInput value={text} onChangeText={setText} placeholder="Add a caption (optional)" placeholderTextColor="rgba(255,255,255,0.6)" style={styles.voiceCaption} maxLength={120}/></View>:mode==="video"?<View style={styles.voiceWrap}><Icon name="videocam" size={54} color="#FFFFFF"/><Text style={styles.voiceLabel}>{video?`Video ready · ${Math.ceil(videoDur)}s / ${maxVideoSeconds}s`:`Blue video Story · up to ${maxVideoSeconds}s`}</Text><Pressable style={styles.videoPick} onPress={pickVideo}><Text style={styles.pickText}>{video?"Choose another video":"Choose video"}</Text></Pressable><TextInput value={text} onChangeText={setText} placeholder="Add a caption (optional)" placeholderTextColor="rgba(255,255,255,0.6)" style={styles.voiceCaption} maxLength={120}/></View>:!image&&<Pressable style={styles.pickPhoto} onPress={pickImage}><Icon name="image" size={44} color="#FFFFFF"/><Text style={styles.pickText}>Tap to choose a photo</Text></Pressable>}
      <View style={[styles.topBar,{top:insets.top+spacing.sm}]}><Pressable onPress={()=>router.back()} style={styles.topBtn}><Icon name="close" size={26} color="#FFFFFF"/></Pressable><Pressable onPress={()=>setAudience(audience==="friends"?"inner":"friends")} style={styles.audToggle}><Icon name={audience==="inner"?"star":"people"} size={16} color="#FFFFFF"/><Text style={styles.audToggleText}>{audience==="inner"?"Inner Circle":"Friends"}</Text></Pressable></View>
    </View>
    <View style={[styles.controls,{paddingBottom:insets.bottom+spacing.md}]}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.modeRow}>{([{k:"text",icon:"text",label:"Text"},{k:"photo",icon:"image",label:"Photo"},{k:"voice",icon:"mic",label:"Voice"},...(canVideo?[{k:"video",icon:"videocam",label:"Video"}]:[])] as any[]).map(m=><Pressable key={m.k} style={[styles.modeBtn,mode===m.k&&{backgroundColor:colors.brandPrimary}]} onPress={()=>{ if(m.k==="photo") pickImage(); else if(m.k==="video") pickVideo(); else setMode(m.k); }}><Icon name={m.icon as any} size={18} color={mode===m.k?colors.onBrandPrimary:colors.onSurfaceTertiary}/><Text style={[styles.modeText,{color:mode===m.k?colors.onBrandPrimary:colors.onSurfaceTertiary}]}>{m.label}</Text></Pressable>)}</ScrollView>{mode!=="photo"&&mode!=="video"&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.colorRow}>{STORY_BG_COLORS.map(color=><Pressable key={color} onPress={()=>setBg(color)} style={[styles.colorDot,{backgroundColor:color},bg===color&&styles.colorSelected]}/>)}</ScrollView>}<Button title="Share to story" onPress={share} loading={busy}/></View>
  </View>;
}

const useStyles=makeStyles(c=>({root:{flex:1,backgroundColor:c.surface},preview:{flex:1,alignItems:"center",justifyContent:"center",overflow:"hidden",backgroundColor:"#111827"},previewImg:{...({position:"absolute",left:0,right:0,top:0,bottom:0} as any)},storyInput:{color:"#FFFFFF",fontFamily:fonts.displayBold,fontSize:30,textAlign:"center",paddingHorizontal:spacing.xl,maxHeight:300,minWidth:"80%"},pickPhoto:{alignItems:"center",gap:spacing.md},pickText:{color:"#FFFFFF",fontFamily:fonts.medium,fontSize:16},videoPick:{paddingHorizontal:spacing.lg,paddingVertical:spacing.sm,borderRadius:radius.pill,borderWidth:1,borderColor:"rgba(255,255,255,.6)"},topBar:{position:"absolute",left:spacing.lg,right:spacing.lg,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},topBtn:{width:40,height:40,borderRadius:20,backgroundColor:"rgba(0,0,0,.35)",alignItems:"center",justifyContent:"center"},audToggle:{flexDirection:"row",alignItems:"center",gap:spacing.xs,backgroundColor:"rgba(0,0,0,.4)",paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radius.pill},audToggleText:{color:"#FFFFFF",fontFamily:fonts.semibold,fontSize:13},voiceWrap:{alignItems:"center",gap:spacing.lg,paddingHorizontal:spacing.xl},recBtn:{width:96,height:96,borderRadius:48,backgroundColor:"rgba(255,255,255,.25)",borderWidth:3,borderColor:"#FFFFFF",alignItems:"center",justifyContent:"center"},voiceLabel:{color:"#FFFFFF",fontFamily:fonts.semibold,fontSize:16},voiceCaption:{color:"#FFFFFF",fontFamily:fonts.medium,fontSize:16,textAlign:"center",borderBottomWidth:1,borderColor:"rgba(255,255,255,.4)",minWidth:200,paddingVertical:spacing.xs},controls:{padding:spacing.lg,gap:spacing.md,backgroundColor:c.surface,borderTopWidth:1,borderTopColor:c.border},modeRow:{gap:spacing.sm,alignItems:"center",padding:4},modeBtn:{flexDirection:"row",alignItems:"center",gap:spacing.xs,paddingVertical:spacing.sm,paddingHorizontal:spacing.lg,borderRadius:radius.sm,backgroundColor:c.surfaceTertiary},modeText:{fontFamily:fonts.semibold,fontSize:14},colorRow:{gap:spacing.sm,paddingVertical:spacing.xs},colorDot:{width:40,height:40,borderRadius:20,borderWidth:2,borderColor:"transparent"},colorSelected:{borderColor:c.onSurface,transform:[{scale:1.1}]}}));
