import { useState } from "react";
import { View,Text,Pressable } from "react-native";
import { KeyboardAwareScrollView } from "react-native-keyboard-controller";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useQueryClient } from "@tanstack/react-query";
import { makeStyles,useTheme,fonts,spacing } from "@/src/theme";
import { Field,Button } from "@/src/components/ui";
import { Icon } from "@/src/components/Icon";
import { useToast } from "@/src/components/Toast";
import { useAuth } from "@/src/context/AuthContext";
import { api } from "@/src/api/client";
export default function AccountContact(){
 const styles=useStyles(),{colors}=useTheme(),router=useRouter(),insets=useSafeAreaInsets(),toast=useToast(),{user,refresh}=useAuth(),qc=useQueryClient();
 const [kind,setKind]=useState<"email"|"phone">(user?.phone?"email":"phone"),[contact,setContact]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[request,setRequest]=useState<string|null>(null),[busy,setBusy]=useState(false),[sentAt,setSentAt]=useState(0);
 function choose(next:"email"|"phone"){setKind(next);setContact("");setCode("");setRequest(null);}
 async function send(){if(!contact.trim()||!password)return toast.show("Enter your new contact and current password","error");if(Date.now()-sentAt<60000)return toast.show("Wait 60 seconds before requesting another code","error");setBusy(true);try{const r=await api.post("/account/contact/request",{kind,contact:contact.trim(),password});setRequest(r.request_id);setCode("");setSentAt(Date.now());toast.show(`Verification code sent to your ${kind}`,"success");}catch(e:any){toast.show(e.message||"Could not send code","error");}finally{setBusy(false);}}
 async function confirm(){if(!/^\d{6}$/.test(code))return toast.show("Enter the six-digit verification code","error");setBusy(true);try{await api.post("/account/contact/confirm",{request_id:request,code});await refresh();await qc.invalidateQueries({queryKey:["me-settings"]});toast.show(`${kind==="phone"?"Phone":"Email"} verified and linked to your account`,"success");router.back();}catch(e:any){toast.show(e.message||"Could not verify contact","error");}finally{setBusy(false);}}
 return <View style={[styles.root,{paddingTop:insets.top}]}><View style={styles.header}><Pressable onPress={()=>router.back()}><Icon name="chevron-back" size={26} color={colors.onSurface}/></Pressable><Text style={styles.title}>Account contact</Text></View><KeyboardAwareScrollView contentContainerStyle={styles.body} keyboardShouldPersistTaps="handled" bottomOffset={20}><Text style={styles.text}>Email: {user?.email||"Not linked"}</Text><Text style={styles.text}>Phone: {user?.phone||"Not linked"}</Text><View style={styles.row}><Button title="Email" variant={kind==="email"?"primary":"secondary"} onPress={()=>choose("email")} disabled={busy}/><Button title="Phone" variant={kind==="phone"?"primary":"secondary"} onPress={()=>choose("phone")} disabled={busy}/></View><Text style={styles.text}>Add or update your {kind}. Your account and purchases stay the same. Enter your current password, then verify the code sent to your new contact.</Text>{!request?<><Field value={contact} onChangeText={setContact} placeholder={kind==="phone"?"Phone with country code, e.g. +966…":"New email address"} keyboardType={kind==="phone"?"phone-pad":"email-address"} autoCapitalize="none" testID="contact-value"/><Field value={password} onChangeText={setPassword} placeholder="Current password" secureTextEntry testID="contact-password"/><Button title="Send verification code" onPress={send} loading={busy} testID="contact-send"/></>:<><Text style={styles.text}>A code was sent to {contact}. It expires in 10 minutes.</Text><Field value={code} onChangeText={setCode} placeholder="Six-digit code" keyboardType="number-pad" maxLength={6} testID="contact-code"/><Button title="Verify and link contact" onPress={confirm} loading={busy} testID="contact-confirm"/><Button title="Resend code" variant="ghost" onPress={send} disabled={busy}/><Button title="Change contact" variant="ghost" onPress={()=>{setRequest(null);setCode("");}} disabled={busy}/></>}</KeyboardAwareScrollView></View>;
}
const useStyles=makeStyles(c=>({root:{flex:1,backgroundColor:c.surface},header:{flexDirection:"row",gap:spacing.md,alignItems:"center",padding:spacing.lg},title:{fontFamily:fonts.display,fontSize:20,color:c.onSurface},body:{padding:spacing.lg,gap:spacing.lg,paddingBottom:50},text:{fontFamily:fonts.text,fontSize:14,lineHeight:21,color:c.onSurfaceSecondary},row:{flexDirection:"row",gap:spacing.md}}));
