import { normalizeExternalUrl, openExternalLink } from "@/src/lib/externalLinks";
import { useEffect,useState } from "react";
import { View,Text,Pressable,ScrollView } from "react-native";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { makeStyles,useTheme,fonts,spacing,radius } from "@/src/theme";
import { Field,Button } from "@/src/components/ui";
import { Icon } from "@/src/components/Icon";
import { useToast } from "@/src/components/Toast";
import { api } from "@/src/api/client";
import { useBlueEntitlements } from "@/src/hooks/useBlueEntitlements";

type Link={label:string;url:string};
export default function BlueLinks(){
 const styles=useStyles();const {colors}=useTheme();const router=useRouter();const insets=useSafeAreaInsets();const toast=useToast();const blue=useBlueEntitlements();const [links,setLinks]=useState<Link[]>([{label:"",url:""},{label:"",url:""}]);const [busy,setBusy]=useState(false);const active=!!blue.data?.blue?.external_links;const limit=blue.data?.blue?.external_links_max||2;
 useEffect(()=>{api.get("/profile/external-links").then((r:any)=>{const x=(r.links||[]).slice(0,limit);setLinks([...x,...Array(Math.max(0,limit-x.length)).fill(null).map(()=>({label:"",url:""}))]);}).catch(()=>{});},[limit]);
 function edit(i:number,key:keyof Link,value:string){setLinks(v=>v.map((x,n)=>n===i?{...x,[key]:value}:x));}
 async function save(){if(!active)return toast.show("Blue Tick is required","error");const clean=links.filter(x=>x.label.trim()||x.url.trim()).map(x=>({label:x.label.trim(),url:x.url.trim()}));if(clean.some(x=>!x.label||!x.url))return toast.show("Each link needs a label and web address","error");setBusy(true);try{await api.post("/profile/external-links",{links:clean.map(x=>({...x,url:normalizeExternalUrl(x.url)}))});toast.show("Profile links updated","success");router.back();}catch(e:any){toast.show(e.message||"Could not save links","error");}finally{setBusy(false)}}
 return <View style={[styles.root,{paddingTop:insets.top}]}><View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Icon name="chevron-back" size={26} color={colors.onSurface}/></Pressable><Text style={styles.title}>Profile Links</Text><View style={{width:40}}/></View><ScrollView contentContainerStyle={styles.body}><View style={styles.info}><Icon name="link" size={24} color={colors.brandPrimary}/><Text style={styles.infoText}>Blue verified accounts can add up to {limit} external links to their profile.</Text></View>{links.slice(0,limit).map((x,i)=><View key={i} style={styles.card}><Text style={styles.label}>Link {i+1}</Text><Field value={x.label} onChangeText={v=>edit(i,"label",v)} placeholder="Label, e.g. Website"/><Field value={x.url} onChangeText={v=>edit(i,"url",v)} placeholder="https://example.com" autoCapitalize="none"/>{!!x.url.trim()&&<Button title="Open link" variant="ghost" onPress={()=>openExternalLink(x.url).catch(e=>toast.show(e.message||"Unable to open link","error"))}/>}</View>)}<Button title="Save profile links" onPress={save} loading={busy} disabled={!active}/>{!active&&<Text style={styles.locked}>This feature unlocks with an active Blue Tick.</Text>}</ScrollView></View>;
}
const useStyles=makeStyles(c=>({root:{flex:1,backgroundColor:c.surface},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderBottomWidth:1,borderBottomColor:c.border},back:{width:40,height:40,alignItems:"center",justifyContent:"center"},title:{fontFamily:fonts.display,fontSize:18,color:c.onSurface},body:{padding:spacing.lg,gap:spacing.lg},info:{flexDirection:"row",gap:spacing.md,alignItems:"center",padding:spacing.lg,backgroundColor:c.surfaceTertiary,borderRadius:radius.lg},infoText:{flex:1,fontFamily:fonts.medium,fontSize:13,lineHeight:19,color:c.onSurfaceSecondary},card:{gap:spacing.sm,padding:spacing.lg,borderWidth:1,borderColor:c.border,borderRadius:radius.lg},label:{fontFamily:fonts.semibold,fontSize:14,color:c.onSurface},locked:{textAlign:"center",fontFamily:fonts.medium,fontSize:13,color:c.muted}}));