import { useState, useEffect } from "react";
import { View, Text, Pressable, ActivityIndicator } from "react-native";
import { KeyboardAwareScrollView } from "react-native-keyboard-controller";
import { Image } from "expo-image";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { makeStyles, useTheme, fonts, spacing, radius } from "@/src/theme";
import { Field, Button } from "@/src/components/ui";
import { Avatar } from "@/src/components/Avatar";
import { Icon } from "@/src/components/Icon";
import { useToast } from "@/src/components/Toast";
import { useAuth } from "@/src/context/AuthContext";
import { api, fileUrl } from "@/src/api/client";
import { pickAndUploadImage, takeAndUploadSelfie } from "@/src/lib/media";

const DEFAULT_COVER="https://images.unsplash.com/photo-1511081692775-05d0f180a065?crop=entropy&cs=srgb&fm=jpg&q=85";
export default function EditProfile(){
 const styles=useStyles(); const {colors}=useTheme(); const insets=useSafeAreaInsets(); const router=useRouter(); const toast=useToast(); const {user,refresh}=useAuth();
 const [fullName,setFullName]=useState(user?.full_name||""); const [bio,setBio]=useState(user?.bio||""); const [location,setLocation]=useState(user?.location||""); const [dateOfBirth,setDateOfBirth]=useState(user?.date_of_birth||""); const [avatar,setAvatar]=useState(user?.avatar||null); const [cover,setCover]=useState(user?.cover||null); const [nameEvidence,setNameEvidence]=useState<string|null>(null); const [avatarEvidence,setAvatarEvidence]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [coverSaving,setCoverSaving]=useState(false);
 const [liveSelfie,setLiveSelfie]=useState<string|null>(null);
 const verified=!!user?.blue_tick_active||!!user?.verified;
 async function captureLiveSelfie(){try{const r=await takeAndUploadSelfie(.8);if(r?.denied)return toast.show("Camera permission needed","error");if(r?.url)setLiveSelfie(r.url);}catch(e:any){toast.show(e.message||"Selfie upload failed","error");}}
 useEffect(()=>{if(user){setFullName(user.full_name||"");setBio(user.bio||"");setLocation(user.location||"");setDateOfBirth(user.date_of_birth||"");setAvatar(user.avatar||null);setCover(user.cover||null);}},[user?.id]);
 async function changeAvatar(){try{const r=await pickAndUploadImage({aspect:[1,1]});if(r?.denied)return toast.show("Photo permission needed","error");if(r?.url)setAvatar(r.url);}catch(e:any){toast.show(e.message||"Upload failed","error");}}
 async function changeCover(){if(coverSaving)return;try{setCoverSaving(true);const r=await pickAndUploadImage({aspect:[16,9]});if(r?.denied)return toast.show("Photo permission needed","error");if(!r?.url)return;await api.post("/profile/edit-v2",{cover:r.url});setCover(r.url);await refresh();toast.show("Cover photo updated","success");}catch(e:any){toast.show(e.message||"Cover photo update failed","error");}finally{setCoverSaving(false);}}
 async function uploadEvidence(kind:"name"|"avatar"){try{const r=await pickAndUploadImage({quality:.8});if(r?.denied)return toast.show("Photo permission needed","error");if(r?.url){kind==="name"?setNameEvidence(r.url):setAvatarEvidence(r.url);toast.show("Supporting document added","success");}}catch(e:any){toast.show(e.message||"Upload failed","error");}}
 async function save(){if(!fullName.trim())return toast.show("Name can't be empty","error");const dob=dateOfBirth.trim();if(dob&&!/^\d{4}-\d{2}-\d{2}$/.test(dob))return toast.show("Date of birth must use YYYY-MM-DD","error");const nameChanged=fullName.trim()!==(user?.full_name||"");const avatarChanged=avatar!==(user?.avatar||null);if(verified&&nameChanged&&!nameEvidence)return toast.show("Add supporting document for the new verified name","error");if(verified&&avatarChanged&&!avatarEvidence)return toast.show("Add supporting document for the new profile photo","error");if(verified&&(nameChanged||avatarChanged)&&!liveSelfie)return toast.show("Take a live selfie for identity review","error");setSaving(true);try{const r=await api.post("/profile/edit-v2",{full_name:fullName.trim(),bio:bio.trim()||null,location:location.trim()||null,date_of_birth:dob||null,avatar, name_evidence_url:nameEvidence,avatar_evidence_url:avatarEvidence,live_selfie_url:liveSelfie});await refresh();toast.show(r?.identity_review_required?"Name/profile photo sent for admin review":"Profile updated","success");router.back();}catch(e:any){toast.show(e.message||"Could not update profile","error");}finally{setSaving(false);}}
 return <View style={[styles.root,{paddingTop:insets.top}]}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.iconBtn}><Icon name="close" size={26} color={colors.onSurface}/></Pressable><Text style={styles.title}>Edit Profile</Text><View style={{width:40}}/></View><KeyboardAwareScrollView contentContainerStyle={{paddingBottom:spacing["2xl"]}} keyboardShouldPersistTaps="handled" bottomOffset={20}>
 <Pressable style={styles.coverWrap} onPress={changeCover} disabled={coverSaving}><Image source={{uri:fileUrl(cover)||DEFAULT_COVER}} style={styles.cover} contentFit="cover"/><LinearGradient colors={["transparent","rgba(0,0,0,0.4)"]} style={styles.coverScrim}/><View style={styles.coverEdit}>{coverSaving?<ActivityIndicator size="small" color="#fff"/>:<Icon name="camera" size={18} color="#fff"/>}<Text style={styles.coverEditText}>{coverSaving?"Updating...":"Change cover"}</Text></View></Pressable>
 <View style={styles.avatarWrap}><Pressable onPress={changeAvatar}><View style={styles.avatarBorder}><Avatar uri={avatar} name={fullName} size={88}/></View><View style={styles.avatarEdit}><Icon name="camera" size={16} color={colors.onBrandPrimary}/></View></Pressable></View>
 <View style={styles.form}>{verified&&<Text style={styles.notice}>Blue verified: name and profile photo changes require admin review. Cover photo can be changed anytime.</Text>}<Text style={styles.label}>Full name</Text><Field value={fullName} onChangeText={setFullName} placeholder="Full name"/>{verified&&fullName.trim()!==(user?.full_name||"")&&<Button title={nameEvidence?"Name document added ✓":"Add name document"} onPress={()=>uploadEvidence("name")}/>} {verified&&avatar!==(user?.avatar||null)&&<Button title={avatarEvidence?"Profile photo document added ✓":"Add profile photo document"} onPress={()=>uploadEvidence("avatar")}/>}{verified&&(fullName.trim()!==(user?.full_name||"")||avatar!==(user?.avatar||null))&&<><Text style={styles.notice}>Upload your ID and take a live selfie. Your current name and photo stay visible until admin approval.</Text><Button title={liveSelfie?"Live selfie added ✓":"Take live selfie"} onPress={captureLiveSelfie}/></>}<Text style={styles.label}>Bio</Text><Field value={bio} onChangeText={setBio} placeholder="Tell your story..." multiline maxLength={160}/><Text style={styles.label}>Location</Text><Field value={location} onChangeText={setLocation} placeholder="Location"/><Text style={styles.label}>Date of birth</Text><Field value={dateOfBirth} onChangeText={setDateOfBirth} placeholder="YYYY-MM-DD"/><Button title="Save changes" onPress={save} loading={saving} style={{marginTop:spacing.lg}}/></View></KeyboardAwareScrollView></View>;
}
const useStyles=makeStyles(c=>({root:{flex:1,backgroundColor:c.surface},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:spacing.lg,paddingVertical:spacing.sm},iconBtn:{width:40,height:40,alignItems:"center",justifyContent:"center"},title:{color:c.onSurface,fontFamily:fonts.display,fontSize:18},coverWrap:{width:"100%",height:160},cover:{width:"100%",height:"100%",backgroundColor:c.surfaceTertiary},coverScrim:{...({position:"absolute",left:0,right:0,top:0,bottom:0} as any)},coverEdit:{position:"absolute",bottom:spacing.md,right:spacing.lg,flexDirection:"row",gap:spacing.xs,backgroundColor:"rgba(0,0,0,.4)",paddingHorizontal:spacing.md,paddingVertical:spacing.xs,borderRadius:radius.pill},coverEditText:{color:"#fff",fontFamily:fonts.medium,fontSize:13},avatarWrap:{paddingHorizontal:spacing.lg,marginTop:-44},avatarBorder:{padding:4,borderRadius:52,backgroundColor:c.surface,alignSelf:"flex-start"},avatarEdit:{position:"absolute",bottom:4,right:4,width:30,height:30,borderRadius:15,backgroundColor:c.brandPrimary,alignItems:"center",justifyContent:"center",borderWidth:2,borderColor:c.surface},form:{paddingHorizontal:spacing.lg,paddingTop:spacing.lg,gap:spacing.sm},label:{color:c.onSurfaceSecondary,fontFamily:fonts.semibold,fontSize:14,marginTop:spacing.sm},notice:{color:c.onSurfaceSecondary,fontFamily:fonts.medium,fontSize:13,lineHeight:19,backgroundColor:c.surfaceTertiary,padding:spacing.md,borderRadius:radius.md}}));